package es.classone.restaurant.web.services;

public enum AuthenticationPolicyType {
	ALL_USERS, AUTHENTICATED_USERS, NON_AUTHENTICATED_USERS, PRIVELEGE1_USERS, PRIVELEGE2_USERS, PRIVELEGE3_USERS, PRIVELEGE4_USERS, PRIVELEGE5_USERS, PRIVELEGE6_USERS, PRIVELEGE7_USERS, PRIVELEGE8_USERS, PRIVELEGE9_USERS;
}
